### ISSUE TITLE
Can we record the talk and play during conference instead of speaking live?

### ISSUE THREAD

**Issue by raukadah** [pythonindia/inpycon2020-tasks#62]
Every conference is going virtual.
Virtual event have one common problem about live interaction with audience. 
In current scenario, speaker comes live and delivers the talk. During the talk, Attendees use the chat system and add their comments and questions there. 
Then at the end of talk, Organizers pull all the questions together and show it on the slides and 
speakers answers the questions.
The problem here is that there is a very less interaction and does not feel inclusive.
Can we keep an option where speaker can pre-record the talk and organizer will play the talk. During that time, speaker
will spark the discussion and interact will everyone so that everyone will feel inclusive.

**Comment by anistark** [comment]
Good idea 👍🏼  Would also have to check on which platform we're going to use to support running videos and do q/a side-by-side. Otherwise, might feel like homework to see the talk offline and then will be kinda like an AMA.

One of the workshop speakers have in-fact reached out saying that he has a recorded workshop and would like to play it. (Full content on this on wg/cfp on zulip.

**Comment by siddharthvipul** [comment]
I like the idea.. we could also have the option to either present online or have pre-recorded.
If we try to do it while mentorship, would be easy to manage (since in this process we will be interacting with speakers 1:1)
The process could go like -> 
* present your talk to a mentor and a volunteer
* take feedback, rectify those
* Record with feedbacks into consideration and share the recording. 

The volunteer goes through the recording to confirm if feedbacks/concerns are rectified. If not, replies with the concern (call with the same mentor can be rescheduled if needed)

Of course, this is just what I am thinking from the top of my head and definitely needs more discussion.
